<?php

namespace Acme\Bundle\ApiBundle\Repository;

/**
 * FollowedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowedRepository extends \Doctrine\ORM\EntityRepository
{
}
